import com.android.build.api.artifact.SingleArtifact
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.aboutlibraries)
}

val gitVersionCode = gradle.extra["gitVersionCode"] as Int
val gitHash = gradle.extra["gitHash"] as String
val gitBranch = gradle.extra["gitBranch"] as String
val buildSuffix = gradle.extra["buildSuffix"] as String
val baseVersionName = gropify.project.app.versionName.replace("\"", "")
val versionCodename = gropify.project.app.versionCodename.replace("\"", "")
val finalVersionName = "$baseVersionName-$buildSuffix"

android {
    buildToolsVersion = gropify.project.android.buildToolsVersion
    namespace = gropify.project.app.packageName
    compileSdk {
        version =
            release(gropify.project.android.compileSdk) {
                minorApiLevel = gropify.project.android.compileSdkMinor
            }
    }

    defaultConfig {
        applicationId = gropify.project.app.packageName
        minSdk = gropify.project.android.minSdk
        targetSdk = gropify.project.android.targetSdk
        versionName = gropify.project.app.versionName
        versionCode = gitVersionCode
        buildConfigField("String", "BUILD_CHANNEL", "\"$buildSuffix\"")
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            val localProperties = Properties().apply {
                val file = rootProject.file("local.properties")
                if (file.exists()) {
                    file.inputStream().use { load(it) }
                }
            }

            fun getProp(key: String): String? =
                localProperties.getProperty(key) ?: (project.findProperty(key) as? String)
                ?: System.getenv(key)

            storeFile = file(getProp("androidStoreFile") ?: "../release-key.jks")
            storePassword = getProp("KEYSTORE_PASSWORD")
            keyAlias = getProp("KEY_ALIAS")
            keyPassword = getProp("KEY_PASSWORD")
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
        }
    }

    buildTypes {
        getByName("debug") {
            signingConfig = signingConfigs.getByName("release")
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
            versionNameSuffix = gradle.extra["versionSuffix"].toString()
        }
    }

    buildFeatures {
        aidl = true
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

androidComponents {
    onVariants(selector().all()) { variant ->
        val variantName = variant.name.replaceFirstChar { it.uppercase() }
        val exportApk = tasks.register<Sync>("export${variantName}Apk") {
            from(variant.artifacts.get(SingleArtifact.APK))
            include("*.apk")
            rename { "SoundMan-v${finalVersionName}.apk" }
            into(layout.buildDirectory.dir("outputs/renamed-apk/${variant.name}"))
        }

        tasks.matching { it.name == "assemble${variantName}" }.configureEach {
            finalizedBy(exportApk)
        }
    }
}

val ensureGropifyAppProperties = tasks.register("ensureGropifyAppProperties") {
    val outputFile = layout.buildDirectory.file(
        "generated/gropify/src/main/hk/uwu/soundman/generated/AppProperties.kt",
    )
    val fallbackGitHash = gitHash
    val fallbackGitBranch = gitBranch
    val fallbackBuildNumber = gitVersionCode
    val fallbackChannel = buildSuffix
    val fallbackVersionName = baseVersionName
    val fallbackCodename = versionCodename
    outputs.file(outputFile)
    outputs.upToDateWhen { false }
    doLast {
        val file = outputFile.get().asFile
        val isFallback = file.exists() && file.useLines { lines ->
            lines.firstOrNull()?.contains("Fallback generated by the app build") == true
        }
        if (!file.exists() || isFallback) {
            file.parentFile.mkdirs()
            file.writeText(
                """
                // Fallback generated by the app build when Gropify's incremental deployer has no output.
                package hk.uwu.soundman.generated

                public object AppProperties {
                    public const val GIT_HASH: String = "$fallbackGitHash"
                    public const val GIT_BRANCH: String = "$fallbackGitBranch"
                    public const val BUILD_NUMBER: Int = $fallbackBuildNumber
                    public const val BUILD_CHANNEL: String = "$fallbackChannel"
                    public const val PROJECT_APP_VERSION_NAME: String = "$fallbackVersionName"
                    public const val PROJECT_APP_VERSION_CODENAME: String = "$fallbackCodename"
                }
                """.trimIndent(),
            )
        }
    }
}

tasks.withType<KotlinJvmCompile>().configureEach {
    dependsOn(ensureGropifyAppProperties)
}
tasks.matching { it.name.startsWith("ksp") }.configureEach {
    dependsOn(ensureGropifyAppProperties)
}

aboutLibraries {
    offlineMode = false
    collect {
        fetchRemoteLicense.set(false)
    }
    export {
        prettyPrint.set(true)
    }
    library {
        duplicationMode.set(com.mikepenz.aboutlibraries.plugin.DuplicateMode.MERGE)
        duplicationRule.set(com.mikepenz.aboutlibraries.plugin.DuplicateRule.GROUP)
    }
}

dependencies {
    implementation(libs.capsule)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.core)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.miuix.ui)
    implementation(libs.miuix.icons)
    implementation(libs.miuix.squircle)
    implementation(libs.miuix.blur)
    implementation(libs.miuix.preference)
    implementation(libs.materialKolor.utilities)
    implementation(libs.navigationevent.compose)
    implementation(libs.backdrop)
    implementation(libs.gson)
    implementation(libs.kotlinx.serialization.json)

    implementation(libs.yukihookapi.api)
    compileOnly(libs.xposed.api)
    ksp(libs.yukihookapi.ksp.xposed)
    implementation(platform(libs.kavaref.bom))
    implementation(libs.kavaref.android)
    implementation(libs.kavaref.core)
    implementation(libs.kavaref.extension)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
}
